version: "3"
services:
  api:
    build: ./backend
    container_name: resistar_api
    volumes:
      - ./backend:/usr/src/app
  frontend:
    build: ./frontend
    container_name: resistar-frontend
    volumes:
      - ./frontend:/app
    command: "sh -c 'yarn install && yarn dev'"
    ports:
      - "3000:3000"
