version: "3"
services:
  frontend:
    build: ./frontend
    container_name: resistar-frontend
    volumes:
      - ./frontend:/app
    command: "sh -c 'yarn install && yarn dev'"
    ports:
      - "3000:3000"
