package graph

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.22

import (
	"context"
	"io"
	"io/fs"
	"os"
	"path"

	"github.com/sijysn/resistar/backend/graph/generated"
	"github.com/sijysn/resistar/backend/graph/model"
)

// AddHistory is the resolver for the addHistory field.
func (r *mutationResolver) AddHistory(ctx context.Context, input model.NewHistory) (*model.History, error) {
	newHistory, err := r.Usecase.AddHistory(ctx, input)
	if err != nil {
		return nil, err
	}
	return newHistory, nil
}

// DeleteHistory is the resolver for the deleteHistory field.
func (r *mutationResolver) DeleteHistory(ctx context.Context, input model.DeleteHistory) (*model.Result, error) {
	result, err := r.Usecase.DeleteHistory(ctx, input)
	if err != nil {
		return nil, err
	}
	return result, nil
}

// AddUser is the resolver for the addUser field.
func (r *mutationResolver) AddUser(ctx context.Context, input model.NewUser) (*model.Result, error) {
	result, err := r.Usecase.AddUser(ctx, input)
	if err != nil {
		return nil, err
	}
	return result, nil
}

// AddGroup is the resolver for the addGroup field.
func (r *mutationResolver) AddGroup(ctx context.Context, input model.NewGroup) (*model.Result, error) {
	result, err := r.Usecase.AddGroup(ctx, input)
	if err != nil {
		return nil, err
	}
	return result, nil
}

// InviteUserToGroup is the resolver for the inviteUserToGroup field.
func (r *mutationResolver) InviteUserToGroup(ctx context.Context, input model.InviteUserToGroupInput) (*model.Result, error) {
	result, err := r.Usecase.InviteUserToGroup(ctx, input)
	if err != nil {
		return nil, err
	}
	return result, err
}

// JoinGroup is the resolver for the joinGroup field.
func (r *mutationResolver) JoinGroup(ctx context.Context, input model.JoinGroup) (*model.Result, error) {
	result, err := r.Usecase.JoinGroup(ctx, input)
	if err != nil {
		return nil, err
	}
	return result, nil
}

// LoginUser is the resolver for the loginUser field.
func (r *mutationResolver) LoginUser(ctx context.Context, input model.LoginUser) (*model.Result, error) {
	result, err := r.Usecase.LoginUser(ctx, input)
	if err != nil {
		return nil, err
	}
	return result, err
}

// LoginGroup is the resolver for the loginGroup field.
func (r *mutationResolver) LoginGroup(ctx context.Context, input model.LoginGroup) (*model.Result, error) {
	result, err := r.Usecase.LoginGroup(ctx, input)
	if err != nil {
		return nil, err
	}
	return result, nil
}

// LogoutGroup is the resolver for the logoutGroup field.
func (r *mutationResolver) LogoutGroup(ctx context.Context) (*model.Result, error) {
	result, err := r.Usecase.LogoutGroup(ctx)
	if err != nil {
		return nil, err
	}
	return result, nil
}

// UploadProfileImage is the resolver for the uploadProfileImage field.
func (r *mutationResolver) UploadProfileImage(ctx context.Context, input model.UploadInput) (*model.UploadPayload, error) {
	const (
		fileDirName string = "file"
		filePerm fs.FileMode = 0o666
	)

	file, err := io.ReadAll(input.Data.File)
	if err != nil {
		return nil, err
	}

	filePath := path.Join(fileDirName, input.Data.Filename)
	if _, err := os.Create(filePath); err != nil {
		return nil, err
	}
	if err := os.WriteFile(filePath, file, filePerm); err != nil {
		return nil, err
	}
	
	pwd, err := os.Getwd()
	if err != nil {
		return nil, err
	}
	return &model.UploadPayload{
		Path: path.Join(pwd, filePath),
	}, nil
}

// Histories is the resolver for the histories field.
func (r *queryResolver) Histories(ctx context.Context, input model.HistoriesQuery) ([]*model.History, error) {
	histories, err := r.Usecase.GetHistories(ctx, input)
	if err != nil {
		return nil, err
	}
	return histories, nil
}

// Users is the resolver for the users field.
func (r *queryResolver) Users(ctx context.Context, input model.UsersQuery) ([]*model.User, error) {
	users, err := r.Usecase.GetUsers(ctx, input)
	if err != nil {
		return nil, err
	}
	return users, nil
}

// Groups is the resolver for the groups field.
func (r *queryResolver) Groups(ctx context.Context, input model.GroupsQuery) ([]*model.Group, error) {
	groups, err := r.Usecase.GetGroups(ctx, input)
	if err != nil {
		return nil, err
	}
	return groups, nil
}

// Amounts is the resolver for the amounts field.
func (r *queryResolver) Amounts(ctx context.Context, input model.AmountsQuery) (*model.Amounts, error) {
	amounts, err := r.Usecase.GetAmounts(ctx, input)
	if err != nil {
		return nil, err
	}
	return amounts, nil
}

// Adjustments is the resolver for the adjustments field.
func (r *queryResolver) Adjustments(ctx context.Context, input model.AdjustmentQuery) ([]*model.Adjustment, error) {
	adjustments, err := r.Usecase.GetAdjustments(ctx, input)
	if err != nil {
		return nil, err
	}
	return adjustments, nil
}

// GroupsWhereUserHasBeenInvited is the resolver for the groupsWhereUserHasBeenInvited field.
func (r *queryResolver) GroupsWhereUserHasBeenInvited(ctx context.Context, input model.GroupsQuery) ([]*model.Group, error) {
	groups, err := r.Usecase.GetGroupsWhereUserHasBeenInvited(ctx, input)
	if err != nil {
		return nil, err
	}
	return groups, nil
}

// Mutation returns generated.MutationResolver implementation.
func (r *Resolver) Mutation() generated.MutationResolver { return &mutationResolver{r} }

// Query returns generated.QueryResolver implementation.
func (r *Resolver) Query() generated.QueryResolver { return &queryResolver{r} }

type mutationResolver struct{ *Resolver }
type queryResolver struct{ *Resolver }
