export const COLOR = {
  PRIMARY_MAIN: "#F68989",
  SECONDARY_MAIN: "#FFBC80",
  TEXT_PRIMARY: "#26262A",
  TEXT_SECONDARY: "rgba(0, 0, 0, 0.6)",
  BACKGROUND_DEFAULT: "#FDFDFD",
  TYPE_DIARY: "#FF9F45",
  TYPE_TRAVEL: "#8FE3CF",
  TYPE_RENT: "#92B4EC",
  TYPE_UTILITY: "#FCE8AA",
  TYPE_COMMUNICATION: "#C5F0A4",
  TYPE_FOOD: "#FD5D5D",
  TYPE_OTHERS: "#CFD2CF",
} as const;
